ALTER TABLE "servico" ADD COLUMN IF NOT EXISTS "categoria" TEXT;
ALTER TABLE "servico" ADD COLUMN IF NOT EXISTS "tempo_estimado" INTEGER;
ALTER TABLE "servico" ADD COLUMN IF NOT EXISTS "ativo" BOOLEAN NOT NULL DEFAULT true;
